

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "next-themes";
import Provider from "./Provider";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>IMDb Clone</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body




        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Provider>
          {/* / Header */}
          <Header />

          {/* Navbar */}
          <Navbar />


          {/*  Search Box */}
          {children}
        </Provider>

      </body>
    </html >
  );
}